### ISSUE TITLE
ModuleNotFound: fn_seq_labeling

### ISSUE THREAD

**Issue by dersuchendee** [lwachowiak/ISCMs#1]
`!source activate bert-for-fn && python -m fn_seq_labeling.labeler evaluate configs/iwcs_experiments_bert_layer/stripped_framesonly_sparse_l12.json --external_data $input_file`

I have this error while trying with a copy of your colab for frame annotation:

```
Traceback (most recent call last):
  File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

I noticed it's because there's a problem when installing the dependencies for the library` bert for framenet`, so it stopped before getting to the "p-starting" libraries. I tried to solve a few but I get the same error, not with pandas but `ipykernel`, which is not even in the requirements.

```
Traceback (most recent call last):
  File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 30, in <module>
    from fn_seq_labeling.datasets import FrameNetDatasetReader, bert_tokenize, init_bert_tokenizer
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/datasets.py", line 17, in <module>
    from fn_seq_labeling.embed_frames import BagOfLexUnitsEmbedder
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/embed_frames.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2355, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'ipykernel'
```

**Comment by lwachowiak** [comment]
Hi @dersuchendee,
I was running the notebook on Google Colab and had the same issue. I had to comment out the nl-core-news-sm library from the conda_env.yaml file from the BERT for FrameNet for everything to install succesfully. Afterwards, I had to install the ipykernel as well using `!source activate bert-for-fn && pip install ipykernel ` in a new notebook cell. 
Then it runs for me (although I did not try to go further as I didn't download the necessary data folder for BERT for Framenet). Let me know if it works for you.
@dgromann did you encounter this issue when you ran the analysis?

**Comment by dersuchendee** [comment]
Now it proceeds, but there's another problem when running `!source activate bert-for-fn && python -m fn_seq_labeling.labeler evaluate configs/iwcs_experiments_bert_layer/stripped_framesonly_sparse_l12.json --external_data $input_file`
:

```
File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 1339, in <module>
    main()
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 1310, in main
    load_hartmann_dev, load_tatoeba_dev, filter_idx)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 119, in __init__
    external_prediction_file)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 184, in _load_train_and_dev_data
    external_prediction_file, load_tatoeba_dev)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 268, in _load_fulltext_data
    self.fulltext_train, = self._load_datasets([train_set_file])
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 1041, in _load_datasets
    datasets = [list(reader.read(file)) for file in datafiles]
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 1041, in <listcomp>
    datasets = [list(reader.read(file)) for file in datafiles]
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 134, in read
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 134, in <listcomp>
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/tqdm/std.py", line 1108, in __iter__
    for obj in iterable:
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/datasets.py", line 143, in _read
    with open(file_path, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/multilabel/fn1.7.fulltext.train.syntaxnet.txt'
0it [00:00, ?it/s]


```

Indeed, there's no folder "data" although there's multilabel, but I can't find where the `_read `function is called from.

**Comment by lwachowiak** [comment]
The Bert for FrameNet [gitlab](https://gitlab.com/gosseminnema/bert-for-framenet/-/tree/master#1-get-data) describes how to get the data in the readme file.

**Comment by dersuchendee** [comment]
Thanks, that's right. Last question: in the code there's no training right? Because I get an error since it can't find a trained model (from the `evaluate `command). So I have add the code in the guide to train first, I guess.

**Comment by dgromann** [comment]
Thanks for reporting these issues - a code cell/line was missing right before Preprocess Data. I have updated the Colab Notebook with the following: 
`!source activate bert-for-fn && python -m fn_seq_labeling.labeler train configs/iwcs_experiments_bert_layer/joint_multilabel_l02.json
`
Could you try again including the above Code? Thanks.

**Comment by dersuchendee** [comment]
In the training phase I get this error now:

```
Tuning 203 parameters
unable to check gpu_memory_mb(), continuing
Traceback (most recent call last):
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/allennlp/common/util.py", line 378, in gpu_memory_mb
    encoding='utf-8')
  File "/usr/local/envs/bert-for-fn/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/envs/bert-for-fn/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvidia-smi', '--query-gpu=memory.used', '--format=csv,nounits,noheader']' returned non-zero exit status 9.
  0% 0/1707 [00:00<?, ?it/s]/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:987: UserWarning: unknown class(es) [1527] will be ignored
  .format(sorted(unknown, key=str)))
Traceback (most recent call last):
  File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 1339, in <module>
    main()
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 1283, in main
    pipeline.train()
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/labeler.py", line 380, in train
    trainer.train()
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
    output_dict = self.model(**batch)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/models.py", line 211, in forward
    tag_logits, loss = self.decoder(embeddings, labels, mask, frame_context_vector, roles_context_vector)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/models.py", line 119, in forward
    loss = self._compute_loss(labels, mask, tag_logits)
  File "/content/drive/MyDrive/Code/Bert_FrameNet/bert-for-framenet/fn_seq_labeling/models.py", line 161, in _compute_loss
    loss = nn.functional.binary_cross_entropy_with_logits(tag_logits, labels, mask)
  File "/usr/local/envs/bert-for-fn/lib/python3.7/site-packages/torch/nn/functional.py", line 2124, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([2, 20, 753])) must be the same as input size (torch.Size([2, 20, 1541]))
  0% 0/1707 [00:01<?, ?it/s]
```

Data that may be relevant:

```
fulltext_train: original length = 3413, reduced length = 3413
3413
100% 3800/3800 [00:00<00:00, 14917.51it/s]
self.vocab= Vocabulary with namespaces:
 	Non Padded Namespaces: {'*tags', '*labels'}
 	Namespace: labels, Size: 1541 

There are 1541 labels
```

**Comment by dgromann** [comment]
It seems to be a problem of the config/data matching. We were actually interested in frame labeling only and used the config we also evaluated on: `stripped_framesonly_sparse_l12` which in the notebook is: 
`!source activate bert-for-fn && python -m fn_seq_labeling.labeler train configs/iwcs_experiments_bert_layer/stripped_framesonly_sparse_l12.json`

Does this work for you?

**Comment by dersuchendee** [comment]
Yes, thank you, that way training and evaluating works! I just have one question on the final part of the code, as I get another error for this part of the code:
```
lemmatized_seed_word = row['SEED_WORD']
                    if "|" in row['STANZA_WORD_DEPS']:
```

As it doesn't find `STANZA_WORD_DEPS`. Where does it come from? I will try to overcome this with an additional condition, but was wondering about this.

```
KeyError: 'STANZA_WORD_DEPS'


The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'STANZA_WORD_DEPS'
```

**Comment by dgromann** [comment]
The last part of the code assumes our own data structure (see annotated_data). If you have a different data structure, please adapt the script. We were only interested in extracting the frames for words related to the seed word by dependency relations (Stanza dependency relations - we additionally, previously extracted those).
